[package]
name = "rust-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
work-queue = "0.1.3"
taskqueue = "0.1.1"
walkdir = "2"